name: DevSecOps CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run tests
      - name: Run tests with pytest
        run: pytest -q

      # 5. Build Docker image
      - name: Build Docker image
        run: docker build -t devsecops-demo:ci .

      # 6. Run Trivy scan
      - name: Security scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-demo:ci
          format: table
          exit-code: 1
          vuln-type: os,library
          severity: CRITICAL,HIGH
